// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQCn5EzLIsInHEMi-FAoaxUWCHWek27c',
    appId: '1:78892305038:android:c4ff9a987eacdcdbf217df',
    messagingSenderId: '78892305038',
    projectId: 'movie-search-55b4e',
    storageBucket: 'movie-search-55b4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBixcblTAspAIsuf1Gj4gQGrQCsUZBeaSk',
    appId: '1:78892305038:ios:43387b26651bc8f4f217df',
    messagingSenderId: '78892305038',
    projectId: 'movie-search-55b4e',
    storageBucket: 'movie-search-55b4e.appspot.com',
    androidClientId: '78892305038-nh7hq9kb4ngp2ege72trsrcnh2qa2ur2.apps.googleusercontent.com',
    iosClientId: '78892305038-i4o2k1ia1ih8hknqol2fvktbcv1d4gvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.suttRound2',
  );
}
